version: '3'
services:
   db:
      image: arm64v8/mysql:8.0
      container_name: admin-sso-mysql
      restart: always
      ports:
        - 13306:3306
      environment:
          MYSQL_DATABASE: AdminSSO
          MYSQL_ROOT_PASSWORD: adminsso
      volumes:
         - ./mysql/conf:/etc/mysql/conf.d
         - ./mysql/data:/var/lib/mysql
