-- upgrade --
CREATE TABLE IF NOT EXISTS `aerich` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `version` VARCHAR(255) NOT NULL,
    `app` VARCHAR(20) NOT NULL,
    `content` JSON NOT NULL
) CHARACTER SET utf8mb4;
CREATE TABLE IF NOT EXISTS `api_permission` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `is_del` BOOL NOT NULL  COMMENT '逻辑删除' DEFAULT 0,
    `created` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `extra_info` JSON NOT NULL  COMMENT '扩展信息',
    `name` VARCHAR(255) NOT NULL  COMMENT 'name',
    `method` VARCHAR(20) NOT NULL  COMMENT '方法',
    `route` VARCHAR(255) NOT NULL  COMMENT '路由',
    `description` LONGTEXT NOT NULL  COMMENT 'desc'
) CHARACTER SET utf8mb4 COMMENT='api权限';
CREATE TABLE IF NOT EXISTS `menu_permission` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `is_del` BOOL NOT NULL  COMMENT '逻辑删除' DEFAULT 0,
    `created` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `node_id` VARCHAR(255) NOT NULL  COMMENT '树节点id',
    `parent_node_id` VARCHAR(255) NOT NULL  COMMENT '树的父节点id',
    `extra_info` JSON NOT NULL  COMMENT '扩展信息',
    `name` VARCHAR(255) NOT NULL  COMMENT 'name',
    `description` LONGTEXT NOT NULL  COMMENT 'desc'
) CHARACTER SET utf8mb4 COMMENT='菜单权限表';
CREATE TABLE IF NOT EXISTS `roles` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `is_del` BOOL NOT NULL  COMMENT '逻辑删除' DEFAULT 0,
    `created` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `extra_info` JSON NOT NULL  COMMENT '扩展信息',
    `name` VARCHAR(255) NOT NULL  COMMENT 'name',
    `description` LONGTEXT NOT NULL  COMMENT 'desc'
) CHARACTER SET utf8mb4 COMMENT='角色表';
CREATE TABLE IF NOT EXISTS `users` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `is_del` BOOL NOT NULL  COMMENT '逻辑删除' DEFAULT 0,
    `created` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `extra_info` JSON NOT NULL  COMMENT '扩展信息',
    `name` VARCHAR(255) NOT NULL  COMMENT 'name',
    `pwd` VARCHAR(255) NOT NULL  COMMENT 'password hash',
    `phone` VARCHAR(255) NOT NULL UNIQUE COMMENT 'phone',
    `is_admin` BOOL NOT NULL  COMMENT 'Background administrator, only for background module' DEFAULT 0,
    `email` VARCHAR(255) NOT NULL  COMMENT 'email'
) CHARACTER SET utf8mb4 COMMENT='用户表';
