-- upgrade --
ALTER TABLE `users` DROP INDEX `name`;
CREATE TABLE IF NOT EXISTS `permission` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `is_del` BOOL NOT NULL  COMMENT '逻辑删除' DEFAULT 0,
    `created` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(255) NOT NULL  COMMENT 'name',
    `desc` LONGTEXT NOT NULL  COMMENT 'desc'
) CHARACTER SET utf8mb4 COMMENT='权限表';;
CREATE TABLE IF NOT EXISTS `roles` (
    `id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    `is_del` BOOL NOT NULL  COMMENT '逻辑删除' DEFAULT 0,
    `created` DATETIME(6) NOT NULL  COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6),
    `updated` DATETIME(6) NOT NULL  COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `name` VARCHAR(255) NOT NULL  COMMENT 'name',
    `desc` LONGTEXT NOT NULL  COMMENT 'desc'
) CHARACTER SET utf8mb4 COMMENT='角色表';;
ALTER TABLE `users` ADD `email` VARCHAR(255) NOT NULL  COMMENT 'email';
ALTER TABLE `users` ADD `phone` VARCHAR(255) NOT NULL UNIQUE COMMENT 'phone';
ALTER TABLE `users` MODIFY COLUMN `pwd` VARCHAR(255) NOT NULL  COMMENT 'password hash';
ALTER TABLE `users` MODIFY COLUMN `name` VARCHAR(255) NOT NULL  COMMENT 'name';
-- downgrade --
ALTER TABLE `users` DROP COLUMN `email`;
ALTER TABLE `users` DROP COLUMN `phone`;
ALTER TABLE `users` MODIFY COLUMN `pwd` VARCHAR(255) NOT NULL  COMMENT '密码hash';
ALTER TABLE `users` MODIFY COLUMN `name` VARCHAR(255) NOT NULL  COMMENT '名称';
DROP TABLE IF EXISTS `permission`;
DROP TABLE IF EXISTS `roles`;
ALTER TABLE `users` ADD UNIQUE INDEX `uid_users_name_6aafa3` (`name`);
